package ua.tqs.coviddata;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CoviddataTest {
  // private WebDriver driver;
  // private Map<String, Object> vars;
  // JavascriptExecutor js;
  // @BeforeEach
  // public void setUp() {
  //   driver = new ChromeDriver();
  //   js = (JavascriptExecutor) driver;
  //   vars = new HashMap<String, Object>();
  // }
  // @AfterEach
  // public void tearDown() {
  //   driver.quit();
  // }
  // @Test
  // void coviddata() {
  //   //go to index page
  //   driver.get("http://localhost:8083");
  //   //go to statistics page and see every country stats
  //   driver.findElement(By.cssSelector(".card:nth-child(1) button")).click();
  //   //insert a country and check its stats
  //   driver.findElement(By.id("countryName")).click();
  //   driver.findElement(By.id("countryName")).sendKeys("uk");
  //   driver.findElement(By.id("searchButton")).click();
  //   //go to history page
  //   //insert country name  and see his stats
  //   driver.findElement(By.id("countryName")).click();
  //   driver.findElement(By.id("countryName")).sendKeys("uk");
  //   driver.findElement(By.id("searchButton")).click();
  //   // insert also a day 
  //   {
  //     WebElement element = driver.findElement(By.id("date"));
  //     Actions builder = new Actions(driver);
  //     builder.doubleClick(element).perform();
  //   }
  //   assertEquals(0, 0);
  //   driver.findElement(By.id("date")).sendKeys("2022-02-06");
  //   driver.findElement(By.id("searchButton")).click();
  //   //close
  //   driver.close();
  // }
}
